name: Docker
on:
  workflow_dispatch: {}
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for the dedicated server docker image
        id: meta_dedicated
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/cardano-scaling/hydra-doom-dedicated
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{version}}
            type=sha
      
      - name: Extract metadata (tags, labels) for the AI docker image
        id: meta_ai
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/cardano-scaling/hydra-doom-ai
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{version}}
            type=sha

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/cardano-scaling
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dedicated image
        uses: docker/build-push-action@v5
        with:
          file: ./dedicated/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta_dedicated.outputs.tags }}
          labels: ${{ steps.meta_dedicated.outputs.labels }}

      - name: Build and push AI image
        uses: docker/build-push-action@v5
        with:
          file: ./ai/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta_ai.outputs.tags }}
          labels: ${{ steps.meta_ai.outputs.labels }}